#!/usr/bin/env bash

kamal app exec -p 'bin/rails runner GenerateSitemapJob.perform_later'

docker run --rm -v "${PWD}:/workdir" --env-file <(env | grep -E '^(KAMAL_|SHIPYRD_)') ghcr.io/shipyrd/shipyrd-gem:latest /shipyrd/bin/$(basename $0)
